const theme = {
     colors: {
          primary: '#fbfd7cff',
          secondary: '#fb6467ff',
          tertiary: '#69c8ecff',
          quaternary: '#526e2dff',
          quintenary: '#e762d7ff',
          success: '#28a745',
          danger: '#dc3545',
          warning: '#ffc107',
          info: '#17a2b8',
          light: '#ffffff',
          dark: '#343a40',
     },
     fonts: {
          primary: 'Roboto, sans-serif',
          secondary: 'Open Sans, sans-serif',
          display: 'Montserrat, sans-serif',
          body: 'Noto Sans, sans-serif',
     },
     fontWeights: {
          light: '100',
          semiLight: '300',
          semiBold: '400',
          mediumSemiBold: '600',
          bold: '800',
     },
     fontSizes: {
          smallest: '0.8rem',
          small: '1.5rem',
          mediumSmall: '2rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
          bigBig: '8rem',
     },
     spacing: {
          smallest: '1rem',
          small: '2rem',
          mediumSmall: '3rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
     },
     height: {
          smallest: '1rem',
          small: '2rem',
          mediumSmall: '3rem',
          medium: '4rem',
          mediumBig: '5rem',
          big: '6rem',
          bigBig: '8rem',
     },
};

export default theme;
